# Example of how access the variables from Pipelines Library
- stage: Development
# [...]
  variables:
  - group: bookstore

# Example of how the variables from Pipelines Library can be used in the pipeline:
# $(Name-of-variable)
# $(SqlServer-Password)