trigger:
- master

pool:
  name: 'default'
  vmImage: 'komputer'
  
steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: |
      **/*.csproj
      !**/InternshipChat.WEB.csproj

- task: CopyFiles@2
  displayName: Add dacpacs to artifact
  inputs:
    Contents: '**\*.dacpac'
    TargetFolder: '$(build.artifactStagingDirectory)/dacpacs'
    flattenFolders: true

- task: CmdLine@2
  displayName: Starting MSSQLLocalDB
  inputs:
    script: |
      sqllocaldb  start MSSQLLocalDB
      sqllocaldb  info MSSQLLocalDB

- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: Publishing Database Project to MSSQLLocalDB
  inputs:
    TaskType: 'dacpac'
    DacpacFile: '$(build.artifactStagingDirectory)/dacpacs/ChatDbProject.dacpac'
    TargetMethod: 'connectionString'
    ConnectionString: 'Server=(localdb)\MSSQLLocalDB;Integrated Security=true;Database=IntegrationTestsDb'

- task: DotNetCoreCLI@2
  displayName: 'Publish packaging'
  inputs:
    command: publish
    publishWebProjects: false
    projects: |
      **/*.csproj
      !**/InternshipChat.WEB.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false 

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'