# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default
  vmImage: komputer

steps:
- script: pwd
  displayName: 'what directory are we in ?'

- script: ls -la
  displayName: 'what files are in this folder?'

- script: dotnet build
  displayName: 'dotnet build'
