trigger:
- master

pool:
  name: 'default'
  vmImage: 'komputer'
  
steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: |
      **/*.csproj
      !**/InternshipChat.WEB.csproj

- task: MSBuild@1
  displayName: 'DB project build'
  inputs:
    solution: '**/ChatDbProject/ChatDbProject.sqlproj'

- task: CopyFiles@2
  displayName: 'Copy dacpac'
  inputs:
    Contents: '**/*.dacpac'
    TargetFolder: '$(build.artifactStagingDirectory)/dacpacs'
    flattenFolders: true

# - task: CmdLine@2
#   displayName: Starting MSSQLLocalDB
#   inputs:
#     script: |
#       sqllocaldb  start MSSQLLocalDB
#       sqllocaldb  info MSSQLLocalDB

- task: DotNetCoreCLI@2
  displayName: 'Publish packaging'
  inputs:
    command: publish
    publishWebProjects: false
    projects: |
      **/*.csproj
      !**/InternshipChat.WEB.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false 

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'